#!/bin/bash
echo "Configuration BoxClient 2 ..."

#interface client
ip addr add 192.168.88.129/24 dev eth0
ip link set dev eth0 up

#interface Routeur FAI
ip addr add 123.51.251.9/29 dev eth1
ip link set dev eth1 up

#activation du routage
echo 1 > /proc/sys/net/ipv4/ip_forward

#ajout de la route par défaut 
ip r a default via 123.51.251.9

#FIREWALL

#NAT
#iptables -t nat -A POSTROUTING -s 192.168.88.128/24 -j MASQUERADE
 
#DHCP
#/etc/init.d/isc-dhcp-server start
