#!/bin/bash

# Make sure we are in the script directory
ScriptDIR=$(cd `dirname $0` && pwd)
if [ $ScriptDIR != $PWD ]; then
   echo "Ce script doit être executé depuis son dossier" 1>&2
   exit
fi

#On récupère le nombre de sessions actives de Yane
C=`sudo ./yane  -l | wc -l`

#On vérifie qu'aucune session n'est déjà lancée
if [ "$C" != "0" ] ; then
  echo "Une session est déjà lancée pour la fermer executez la commande:"
  echo "   STOP"
  exit

else
  #On copie les scripts dans le dossier partagé du Docker correspondant
  cp ./scripts/BoxClient1 ./files/BoxClient1/etc/scripts/init
  cp ./scripts/BoxClient2 ./files/BoxClient2/etc/scripts/init
  cp ./scripts/BoxClient3 ./files/BoxClient3/etc/scripts/init
  cp ./scripts/RouteurFAIAcces ./files/RouteurFAIAcces/etc/scripts/init
  cp ./scripts/RouteurFAIInterconnexion ./files/RouteurFAIInterconnexion/etc/scripts/init
  cp ./scripts/RouteurFAIServices ./files/RouteurFAIServices/etc/scripts/init
  cp ./scripts/Web ./files/Web/var/scripts/init
  cp ./scripts/DNS ./files/DNS/etc/scripts/init
  cp ./scripts/FTP ./files/FTP/etc/scripts/init
  echo 'Chargement des VM..'
  #On lance Yane
  sudo ./yane > /dev/null
  exit
fi
