#!/bin/bash
echo "Configuration R_FAI_Service ..."

#interface Routeur FAI Inter
ip addr add 123.51.251.146/28 dev eth0
ip link set dev eth0 up

#interface Serveur DNS
ip addr add 123.51.251.161/28 dev eth1
ip link set dev eth1 up

#interface Serveur WEB
ip addr add 123.51.251.177/28 dev eth2
ip link set dev eth2 up

#interface Serveur FTP
ip addr add 123.51.251.193/28 dev eth3
ip link set dev eth3 up
