#!/bin/bash
echo "Configuration R_FAI ..."

#interface BoxClient1
ip addr add 123.51.251.2/29 dev eth1
ip link set dev eth1 up

#interface BoxClient2
ip addr add 123.51.251.10/29 dev eth2
ip link set dev eth2 up

#interface BoxClient3
ip addr add 123.51.251.18/29 dev eth3
ip link set dev eth3 up

#interface Routeur d'Interconnexion Régional (RRI)
ip addr add 123.51.251.129/28 dev eth0
ip link set dev eth0 up