#!/bin/bash
echo "Configuration Client 3 ..."

## STATIQUE ##

#interface BOX
ip addr add 192.168.88.130/24 dev eth0
ip link set dev eth0 up

#ajout de la route par défaut
# ip route add default via 192.168.88.129 NON!!



## DYNAMIQUE ##

# DHCP
#dhclient eth0

#ajout de la route par défaut
#ip route add default via 192.168.88.129/24